frequency_bands:
  Delta:
  - 0.5
  - 4
  Theta:
  - 4
  - 8
  Alpha:
  - 8
  - 13
  Beta:
  - 13
  - 30
initial_params:
  merged_episodes: false
  bis_threshold: 70
  mac_threshold: 0.8
  min_episode_length: 20
  refractory_time: 5
  fixed_window_size: 20
  overlap: 0.0
current_params:
  merged_episodes: false
  bis_threshold: 70
  mac_threshold: 0.8
  min_episode_length: 20
  refractory_time: 5
  fixed_window_size: 25
  overlap: 0.0
