root: # Root of the relative structure of Files
    faw: # Subsets with episodes of fake awakeness (FAW)
        name: "FAW_subsets"
    initial_data: # Initial raw data from source
        name: "Initial_data"
        children:
            combined_raw_data:
                name: "vitaldb_csvprocessed_BIS_BIS_SR_MAC" # combined tracks of bis, bis_sr and mac
            raw_eeg_mat:
                name: "vitalDB_mat_EEG" # Raw EEG tracks
    features: # Features and related data (like PSDs for freq domain features)
        name: "Features"
        children:
            psds:
                name: "PSD" # Power Spectrum Densities
            bandpower:
                name: "Rel_bandpower" # Bandpowers relative to spectrum range
            shannon_entropy:
                name: "Shannon_entropy" # Spectral shannon entropy
            spectral_skewness:
                name: "Spectral_skewness" # spectral skewness
            spectral_kurtosis:
                name: "Spectral_kurtosis" # spectral kurtosis
            mean:
                name: "Mean" # Mean for EEG time domain
            variance:
                name: "Variance" # Variance for EEG time domain
            amplitude:
                name: "Amplitude" # Amplitude of EEG time domain
            sample_entropy:
                name: "Sample_entropy" # Sample Entropy in time domain
            permutation_entropy:
                name: "Permutation_entropy" # Permutation Entropy in time domain
            fuzzy_entropy:
                name: "Fuzzy_entropy" # Fuzzy Entropy in time domain
    plots:
        name: "Plots"
    filtered_data:
        name: "Filtered"
    normalized_data:
        name: "Normalized"
    test_and_train_data:
        name: "Test_and_train"
        children:
            feature_sets:
                name: "Feature_sets" # Aggregated features
            splits:
                name: "Splits" # Test and train sets derived from aggregated feature data
    models:
        name: "Models"
        children:
            svm:
                name: "SVM"
            rf:
                name: "RF"
            k_nn:
                name: "KNN"
            lda:
                name: "LDA"
            xg_boost:
                name: "XGBoost"
    results: # Classification results and related metrics
        name: "ML_Results"
        children:
            svm:
                name: "SVM"
            rf:
                name: "RF"
            k_nn:
                name: "KNN"
            lda:
                name: "LDA"
            xg_boost:
                name: "XGBoost"
    metadata_analysis: # Results of classification metadata analyses
        name: "Metadata_analysis"
        children:
            svm:
                name: "SVM"
            rf:
                name: "RF"
            k_nn:
                name: "KNN"
            lda:
                name: "LDA"
            xg_boost:
                name: "XGBoost"
    run_metadata: # Metadata of pipeline runs
        name: "Run_metadata"
        children:
            svm:
                name: "SVM"
            rf:
                name: "RF"
            k_nn:
                name: "KNN"
            lda:
                name: "LDA"
            xg_boost:
                name: "XGBoost"
    further_analysis: # Various Analyses around this project
        name: "Further_analysis"
        children:
            psd:
                name: "PSD"
            pca:
                name: "PCA"
            k_means:
                name: "Kmeans"
            stat_diff:
                name: "Statistical_difference"
            subset_runs:
                name: "Subset_runs"

    global_outliers: # "Outliers" from the expected outcome gathered over multiple runs
        name: "Global_outliers"

    metadata:
        name: "metadata_vitaldb" # File with metadata for all patients
    awake_times:
        name: "anestart_analysis_results" # File with timeframes of awakeness for all patients